[pytest]
testpaths = ngo_homesuite
addopts = --maxfail=10 -v --timeout=60 --timeout=60
filterwarnings =
	error::DeprecationWarning
	ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning:flask_login\.login_manager
