[pytest]
testpaths = ngo_homesuite
addopts = --maxfail=10 -v
filterwarnings =
	error::DeprecationWarning
	ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning:flask_login\.login_manager
